Update appium-android.yml

diff --git a/.github/workflows/appium-android.yml b/.github/workflows/appium-android.yml
--- a/.github/workflows/appium-android.yml
+++ b/.github/workflows/appium-android.yml
@@ -15,7 +15,7 @@ jobs:
        api-level:  [25]
        target:  [default]
     env:
-      ANDROID_HOME: /Users/yourusername/Library/Android/sdk
+      ANDROID_HOME: /Users/username/Library/Android/sdk
     steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 17
@@ -23,15 +23,6 @@ jobs:
       with:
         java-version: 17
         distribution: 'adopt'
-
-    - name: Set up Android SDK
-      run: |
-       export ANDROID_SDK_ROOT=$ANDROID_HOME
-       export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH
-       echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
-       echo "PATH: $PATH"
-       ls -l $ANDROID_SDK_ROOT/tools/bin
-       sdkmanager --install 'build-tools;29.0.2' 'platform-tools' 'platforms;android-25' 'emulator' || { echo "Error: Android SDK installation failed"; exit 1; }
        
     - name: Set up Node.js
       uses: actions/setup-node@v3
@@ -41,6 +32,16 @@ jobs:
       run: |
         npm install -g appium@1.20.2
         appium -v
+    
+    - name: Set up Android SDK
+      run: |
+       export ANDROID_SDK_ROOT=$ANDROID_HOME
+       export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH
+       echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
+       echo "PATH: $PATH"
+       ls -l $ANDROID_SDK_ROOT/tools/bin
+       sdkmanager --install 'build-tools;29.0.2' 'platform-tools' 'platforms;android-25' 'emulator' || { echo "Error: Android SDK installation failed"; exit 1; } 
+    
     - name: Run Appium Tests
       uses: reactivecircus/android-emulator-runner@v1
       with:
