Update appium-android.yml

diff --git a/.github/workflows/appium-android.yml b/.github/workflows/appium-android.yml
--- a/.github/workflows/appium-android.yml
+++ b/.github/workflows/appium-android.yml
@@ -25,9 +25,9 @@ jobs:
         distribution: 'adopt'
     - name: Set up Android SDK
       run: |
-       export ANDROID_SDK_ROOT=$ANDROID_HOME
-       export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH
-       sdkmanager --install 'build-tools;29.0.2' 'platform-tools' 'platforms;android-25' 'emulator' && echo "Android SDK Installed successfully"
+        export ANDROID_SDK_ROOT=$ANDROID_HOME
+        export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH
+        sdkmanager --install 'build-tools;29.0.2' 'platform-tools' 'platforms;android-25' 'emulator' || { echo "Error: Android SDK installation failed"; exit 1; }
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
